sudo: false

language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "pypy3"

install:
  - python setup.py install
  - pip install codecov

script:
  - python setup.py test --addopts --cov

after_success:
  - codecov
